### ISSUE TITLE
Support for equations

### ISSUE THREAD

**Issue by yves-chevallier** [heigvd-teaching-tools/online-test-platform#209]
Currently, the platform doesn't support LaTeX equations. In another project, I used the very powerful https://github.com/markdown-it/markdown-it 

It comes with plenty of plugins such as https://github.com/goessner/markdown-it-texmath 

The goal is to allow equations such as : 

$$ x_{1,2} = -b \pm \frac{\sqrt(b^2 - 4\cdot a\cdot c}{2a} $$

**Comment by Ovich** [comment]
@yves-chevallier implemented
