### ISSUE TITLE
Limit number of answers for a multiple choice question

### ISSUE THREAD

**Issue by yves-chevallier** [heigvd-teaching-tools/online-test-platform#219]
Here's the revised version of the GitHub issue, with corrected grammar and spelling:

When writing a multiple choice question, several scenarios arise:

1. One single choice accepted: the student cannot select more than one answer.
2. Multiple choices accepted: the student can select as many choices as they like without knowing the number of correct answers.
3. Multiple choices accepted with specified answers: the student must select `M` answers from `N` options.
4. Additionally, we could improve the autograding process. Several cases are possible:

No points are given if the answer is incorrect.
Each correct answer awards a percentage of the total point score (e.g., 2 correct answers out of 4 expected: 50% of the points).

Proposed additions to the options field include:

- `{checkbox}` Limit selections to `{int}` option(s).
- `{checkbox}` Display the number of correct choices expected to the student.
- `{checkbox}` Grade proportional to the number of correct answers.

With the first option enabled, the student cannot select more than `M` answers.
With the second option enabled, the student could receive a message like: `1 correct answer expected.`
With the third option enabled, if 4 selections are expected but the student provides only 1 correct answer, they would be awarded 25% of the total points for the question.

**Comment by Ovich** [comment]
@yves-chevallier The limiter is implemented.
